### ISSUE TITLE
Help Varshitha on getting up to date with the current deployments through the git.

### ISSUE THREAD

**Issue by ashrith-UMB** [UMB-CS682-Team-02/tracker#14]
Objective:
Help Varshitha on getting up to date with the current deployments through the git and make the demo tracker work on her local machine with the latest deployments of other team mates.

**Comment by ashrith-UMB** [comment]
Picked up by @ashrith-UMB on 7th March @ thursday.

**Comment by ashrith-UMB** [comment]
1) Varshitha is able to checkout from the test branch
2) Varshitha is able to change from main to test branch and vis versa.

**Comment by rouilj** [comment]
Do you know if she is able to commit a change?
E.G. she could commit her chart template.

**Comment by ashrith-UMB** [comment]
Will check if she's able to commit her changes in to the git and update here.

**Comment by ashrith-UMB** [comment]
@varshi-123 is able to commit changes to the current git.
