### ISSUE TITLE
Remove all the IDs and add relevant labels in the new Stacked chart.

### ISSUE THREAD

**Issue by Pratik0116** [UMB-CS682-Team-02/tracker#16]
**Task Description:**
Enhance the chart by adding labels for better readability and visual appeal.

**Task Details:**
Identify key data points on the chart.
Determine appropriate labels for each data point.
Implement labels using the charting library's labeling feature.
Ensure labels are clearly visible and do not clutter the chart.
Test the chart with the new labels to ensure they enhance understanding without distracting from the data.

**Expected Outcome:**
The chart will be more informative and visually appealing with the addition of labels, improving user comprehension and overall presentation.

**Comment by rouilj** [comment]
Hi Pratik:

What does `Remove all the IDs` mean? Do you mean the #chart.-df57b3f9-... uuid's added to the charts by pygal?

When writing these make the work understandable to your teammates.
When you create the issue you are providing the documenation needed to complete the work.

This also has the real-life benefit that you may work on a ticket 6 months after you created it. While
you understand the problem well enough now are you going to remember what it is 6 months from now?

For an example of what I mean see:
  https://issues.roundup-tracker.org/issue2551326
or
  https://issues.roundup-tracker.org/issue2551113
which require some domain knowledge, but they provide details about the expected outcome, possible implementation, and the subsystem/section of the code to work on.
