### ISSUE TITLE
Create a link in issue_index.html to view Stacked bar chart and linked it to it's register action.

### ISSUE THREAD

**Issue by Pratik0116** [UMB-CS682-Team-02/tracker#18]
**Task Description:**
Create a button in the issue_index.html file to view the Stacked Bar Chart and link it to its corresponding register action.

**Task Details:**
Edit the issue_index.html file to include a button for viewing the Stacked Bar Chart.
Link the button to the register action for the Stacked Bar Chart.
This registration should trigger the generation and display of the Stacked Bar Chart upon button click.

**Expected Outcome:**
Users visiting the issue index page will have the option to view the Stacked Bar Chart by clicking the designated button. Upon clicking, the Stacked Bar Chart will be generated and displayed, providing users with a visual representation of the data.

**Comment by rouilj** [comment]
I would not link to the action. Instead plan on calling the issue.chart.html template.

Also we have been using a link rather than a button.
