### ISSUE TITLE
Create a new Multi Bar Chart instead of Stacked Bar Chart.

### ISSUE THREAD

**Issue by Pratik0116** [UMB-CS682-Team-02/tracker#19]
**Task Description:**
Create a new class for a Multi Bar Chart in the chart.py file and register it with the existing charting framework.

**Task Details:**
Develop a new class named MultiBarChart in the chart.py file.
Implement the necessary methods and attributes for generating multi-series bar charts.
Ensure the class follows the conventions and structure of the existing charting classes.
Enable displaying multiple data series as separate bars within each category.
Implement methods to retrieve data for the chart, considering the possibility of reusing these methods for other chart types.
Integrate the MultiBarChart class with the charting framework by registering it appropriately.

**Expected Outcome:**
The addition of the MultiBarChart class and its registration within the charting framework will expand the available chart types, providing users with the ability to create visually appealing and informative multi-series bar charts for their data visualization needs.

**Comment by rouilj** [comment]
If your stacked bar chart is integrated well, this should be almost trivial as the format of the plot data is the same from what I can tell.
