### ISSUE TITLE
Clicking on a link in the chart should open the next screen in the same tab/window.

### ISSUE THREAD

**Issue by rouilj** [UMB-CS682-Team-02/tracker#28]
Currently when you click on a pie wedge/bar or click on the link shown in the popup when hovering over a chart value component you get a new window.

Change this so the drill down opens in the same window/tab.

**Comment by ashrith-UMB** [comment]
Now, while clicking on the link in the charts will not be redirected to a new tab and they will be opened in the same tab.

commit : https://github.com/UMB-CS682-Team-02/tracker/commit/a62e2fbb7aa1ae652f401082f43c4ca7e49ebcc5
