### ISSUE TITLE
Update load_tracker.py and Add README.txt for PYTHONPATH Setup

### ISSUE THREAD

**Issue by Pratik0116** [UMB-CS682-Team-02/tracker#4]
Objective:
- Integrate PYTHONPATH functionality into the load_tracker.py script for dynamic path configuration, ensuring compatibility across team members' environments.
- Create a README.txt file detailing instructions on setting up PYTHONPATH for seamless script execution.

Actions Taken:
- Updated the load_tracker.py script to incorporate PYTHONPATH functionality, allowing for dynamic configuration of file paths based on the environment's settings, promoting compatibility across team members' systems.
- Added a README.txt file containing instructions on setting up PYTHONPATH, facilitating ease of use and understanding for team members.

Additional Details:
- The integration of PYTHONPATH functionality in load_tracker.py enhances the script's adaptability to different directory structures and configurations, fostering collaborative development among team members.
- The README.txt file provides clear and concise instructions on setting up PYTHONPATH, ensuring seamless execution of the script for all team members.

Next Steps:
- Conduct thorough testing of the updated load_tracker.py script to verify seamless functionality and compatibility across diverse environments.
- Communicate the presence and importance of the README.txt file to team members, emphasizing the necessity of setting up PYTHONPATH for script execution.
- Monitor the effectiveness of the README.txt file in guiding team members through the PYTHONPATH setup process, addressing any questions or concerns as needed.

**Comment by rouilj** [comment]
I am going to claim ashrith fixed this in #7. Closing.
