### ISSUE TITLE
Charting should support grouping by boolean properties (depends on issue 41)

### ISSUE THREAD

**Issue by rouilj** [UMB-CS682-Team-02/tracker#42]
Note issue #41 must be complete before working on this.

Currently we can only draw charts by grouping on a field that is a Link or Multilink type.

Extend charting to include grouping by a property of Boolean type.
In the database, a Boolean can be in one of three states: True, False, Not Set. 

Modify chart.py so that a grouped property of type Boolean is permitted. It should behave
as though the Boolean property was a linked property with three values: True, False, Not Set.

**Comment by ashrith-UMB** [comment]
We can now use charting options for grouping with Boolean property.

Commit : https://github.com/UMB-CS682-Team-02/tracker/commit/5dce18943d63cd53bf7bcab3a6d168f769bf4e97
