### ISSUE TITLE
Issues marked done are not merged to main branch.

### ISSUE THREAD

**Issue by rouilj** [UMB-CS682-Team-02/tracker#45]
An issue should not be marked done until it is merged and tested on the main branch.

For example #42, and #41 are not on main branch. They seem to be only on the test branch.

**Comment by ashrith-UMB** [comment]
I understood @rouilj .

Apologies for not moving it earlier.
I have merged the working code into main branch from test.

pull request : https://github.com/UMB-CS682-Team-02/tracker/pull/46
