### ISSUE TITLE
Is html/issue.chart.html still needed now that _generic.chart.htm has been created?

### ISSUE THREAD

**Issue by rouilj** [UMB-CS682-Team-02/tracker#47]
It looks like some cleanup needs to happen. Does index.chart.html do anything that _generic.chart.html doesn't do?
Of so let's move those things to _generic.chart.html and remove index.chart.html.

Also check that directions for deploying charts to a new tracker are correctly updated for the removal of index.chart.html.

When this is merged to main this ticket can be closed.

**Comment by ashrith-UMB** [comment]
issue.chart.html file has been deleted and pushed to main.

https://github.com/UMB-CS682-Team-02/tracker/pull/53
