### ISSUE TITLE
Document chart url so somebody can craft a chart display by hand

### ISSUE THREAD

**Issue by rouilj** [UMB-CS682-Team-02/tracker#56]
In today's standup, I showed creating a chart of queries grouped by user.

I was able to build that because I knew the url parameters that would generate a chart. These should be documented
and examples given in a tutorial style that even a college professor (not you Ken 8-)  can understand.

This will also be transferred to https://wiki.roundup-tracker.org for a how to use guide for your groups work.

**Comment by rouilj** [comment]
By the time the tutorial is complete the user should be able to craft and understand a url like:

http://localhost:8080/demo/query?@template=chart&@charttype=barchart&@group=creator

to generate a bar chart to display which users. They should be able to change it to display a piechart
and they should be able to group by both creator and private_for fields using something like:

http://localhost:8080/demo/query?@template=chart&@charttype=barchart&@group0=creator&@group1=private_for

(note until #65 is closed this may not work as expected)

**Comment by rouilj** [comment]
See also #67 for queries to add to your tracker to allow testing of charting using queries.

**Comment by rouilj** [comment]
157cf48 has some additional code that I commented on. Please be prepared to answer in standup.

**Comment by ashrith-UMB** [comment]
I have replied to the comment given on the commit.
Please do correct me if I've done anything wrong.

**Comment by rouilj** [comment]
This looks fine. #81 will use the results from your work.
