### ISSUE TITLE
Updating methods to take arguments from dropdown list and generate chart with any 2nd level of grouping selected by user.

### ISSUE THREAD

**Issue by Pratik0116** [UMB-CS682-Team-02/tracker#59]

**Comment by rouilj** [comment]
Pratik can you add a bit more detail here? What is the input, what is the expected output and what is the current output? Also what dropdown list are you referring to?

**Comment by rouilj** [comment]
Pratik, is this now on main?

**Comment by Pratik0116** [comment]
Yes I have merged it into main branch
