### ISSUE TITLE
Refactor get_data_from_query - change/clarify variable naming and values.

### ISSUE THREAD

**Issue by rouilj** [UMB-CS682-Team-02/tracker#62]
<s>Why are there two functions: `get_data_from_query` and  `get_sample_data_from_query`?
What makes them different? Under what circumstances are they called?</s>

<s>Rename `get_sample_data_from_query` to better describe why it exists and what role it plays.</s>

<s>In `get_sample_data_from_query of the current chart.py on main I see code like:
```
            status_id = cl.get(nodeid, 'status')  # Get the status of the issue
            title = db.getclass('priority').get(title_id, 'name')  # Get the name of the priority
            status = db.getclass('status').get(status_id, 'name')
            data[title][status] += 1  # Increment count for the specific title and status
```
shouldn't instances of `'status'`, and `'priority'` be the group[0] and group[1] names?

If so than the variable names `status` and `title` should be changed to match the contents of these variables.

This seems to be a holdover from the original less flexible single group implementation.</s>

**Comment by Pratik0116** [comment]
Sorry John, I commit the code but forget to push it. Now it is on the main branch.
