### ISSUE TITLE
Documentation on how to launch the Demo Tracker

### ISSUE THREAD

**Issue by ashrith-UMB** [UMB-CS682-Team-02/tracker#7]
Objective :
Need to create a simple document which can illustrate a normal user to launch the demo tracker.

**Comment by ashrith-UMB** [comment]
Need to merge both the Readme.txt(info about load tracker init) and Launching the tracker.txt into one.

**Comment by ashrith-UMB** [comment]
Merged both the files into README.txt

**Comment by rouilj** [comment]
This is good enough for developers. At this point we need to work on docs for tracker admins.
Closing.
