### ISSUE TITLE
Drill down by clicking on a bar/wedge opens page in new window/tab - should be same tab

### ISSUE THREAD

**Issue by rouilj** [UMB-CS682-Team-02/tracker#76]
The charts with just one group (bar, pie, horizontalbar but not stacked/multibar) are opening in a new window and not in the same window when drilling down.

Please fix this.

**Comment by rouilj** [comment]
Also add a test to @varshi-123's test code to detect the working case:

  find all `a` tags with `xlink:href` and verify that the target property on the `a` is correct

Work with @varshi-123 to commit your test.

**Comment by ashrith-UMB** [comment]
Clicking on a bar/wedge now will open in the same tab.
commit : https://github.com/UMB-CS682-Team-02/tracker/commit/0fca0bb395e8d0219bba50a63a69a190500c5424

**Comment by rouilj** [comment]
LGTM
