### ISSUE TITLE
Clicking on a bar/wedge doesn't filter the new index page

### ISSUE THREAD

**Issue by rouilj** [UMB-CS682-Team-02/tracker#77]
When clicking on the bar or wedge for a single group chart (it works for stacked and multibar charts),
the URL is incorrectly formed.

I see:
```
http://localhost:8080/demo/issue?@template=index&@columns=id,activity,title,creator,assignedto,status&@sort=-activity&@group=priority&@pagesize=50&@startwith=0&status=-1,1,2,3,4,5,6,7&@filter=status,priority,priority&[%27priority%27]=urgent
```

Note the `[%27priority%27]=urgent` (%27 => ') It looks like the list of groups is being assigned and not the group member. Replacing `['priority'=urgent` with `priority=urgent` in the URL properly filters the drilldown.

The commit to fix this should also modify the test code created by @varshi-123 to detect the incorrect URL.

**Comment by Pratik0116** [comment]
I think my recent changes which I made to solve issue #62 created this bug and I have made some changes into file and have push those into main. This solves the problem so kindly review it. 
commit - 7de7fd9

**Comment by rouilj** [comment]
LGTM
