### ISSUE TITLE
Work on debugging the code

### ISSUE THREAD

**Issue by ashrith-UMB** [UMB-CS682-Team-02/tracker#9]
Objective:
Work on debugging the code and try to explain it to the team if required.

**Comment by ashrith-UMB** [comment]
Picked up by @ashrith-UMB

**Comment by rouilj** [comment]
Which code are you debugging?

**Comment by ashrith-UMB** [comment]
I am currently going through get_data_from_query function in the chart script.
I have also realized that there are 2 tickets open for the same task(this one and https://github.com/UMB-CS682-Team-02/tracker/issues/13).

will be considering this as a duplicate and close it.
